### ISSUE TITLE
Hardware SPI

### ISSUE THREAD

**Issue by epollari** [Andy4495/TLC591x#3]
@Andy4495,

I tweaked your library to support hardware SPI. It's not a major improvement, but as I happened to have a rudimentary sketch for the STP08DP05 (very similar to the TLC5916) that used SPI, I had to give it a try. Another enhancement of mine -- perhaps a more worthwhile one -- is PWM output on /OE, which allows you to set the brightness of the LEDs.

I tested the tweaked library on a WeMos D1 R2 (an Arduino form-factor ESP8266). The display is self-made, with four 1" 7-segment LEDs.

Let me know if you want to review the code.

**Comment by Andy4495** [comment]
Sure - do you want to open a pull request?

**Comment by epollari** [comment]
Can do, but I have another idea for an enhancement. Just give me a couple of days.

**Comment by philippedc** [comment]
Hi, I've done this to allow to dim the display:

//  TLC5916 shift register actions definition
#define oeOFF    digitalWrite(oePin, HIGH)   // display OFF
#define oeON     digitalWrite(oePin, LOW)    // display ON
#define leOFF    digitalWrite(lePin, LOW)    // latch OFF
#define leON     digitalWrite(lePin, HIGH)   // latch ON
#define clkOFF   digitalWrite(clkPin, LOW)   // clock LOW
#define clkON    digitalWrite(clkPin, HIGH)  // clock HIGH


//
// DigitDimming() : dim the digits display according to LDR sensor
//_____________________________________________________________________________________________

void DigitDimming() {

// 1- TLC5916 enter in special mode 
  oeOFF; clkON; clkOFF;
  oeON;  clkON; clkOFF;
  oeOFF; clkON; clkOFF; 
  leON;  clkON; clkOFF;
  leOFF; clkON; clkOFF;

// 2- send a 6+1 bits number (from 0 to 63 + range 25-50% / 50-100%) for the dimming value
  int ldr, dim;
  if( ldrDimming ) {
    ldr = 170 + ldrThreshold - (analogRead(ldrPin))/8;
    dim = (ldr + digitDefaultBrightness)/2;
    if( dim < 80 ) dim = 80;
    if( dim > 127 ) dim = 127;
  }
  else dim = digitDefaultBrightness;
  

  for(byte i=0; i<6; i++) {                // send the 7 bits dimming value to the 6 digits
    for(byte j=0; j<7; j++) {
      digitalWrite( sdPin, ((dim >> j) & 1));
      clkON; clkOFF;
    }
    digitalWrite( sdPin, HIGH);             // the 7th bit is always 1
    clkON; clkOFF;
  }
  leON; leOFF;

// 3- return back in normal mode
  oeOFF; clkON; clkOFF; 
  oeON;  clkON; clkOFF;
  oeOFF; clkON; clkOFF; clkON; clkOFF; clkON; clkOFF;
  oeON;

}      // end of DigitDimming()

**Comment by epollari** [comment]
Bonsoir Philippe,

Good to know.

However, it's easier to do it with PWM on /OE, like this:

void TLC591x::displayBrightness(unsigned int n) {
  if (OE_pin != NO_PIN) {
    analogWrite(OE_pin, n);
    PWM_val = n;
   }
}

I don't have a choice but to use my method since I also have display controller that uses the STP08DP05. That chip lacks a special mode that allows one to set the brightness.

**Comment by philippedc** [comment]
@epollari your're right it is the simplest way, but it may have some circumstances where PWM / analogWrite() doesn't work properly with interruptions / some ws2812 libraries for instance. So it is a good idea to use special TLC591x features which propose special mode to code the dimming, and/or to detect short circuits that allow push buttons connected in parallels with the digit segments.

**Comment by Andy4495** [comment]
I added new methods normalMode() and specialMode() inspired by @philippedc, and displayBrightness() from @epollari 

~~I don't have a setup to test these updates at the moment. Let me know if you are able to try it out and if there are any issues.~~
I have now tested the updates and added example code using the new methods.

**Comment by Andy4495** [comment]
Hardware SPI support has been added as of v1.3.0
