### ISSUE TITLE
LEDs "blipping" during data push

### ISSUE THREAD

**Issue by kestasli** [Andy4495/TLC591x#8]
Hi, thanks for the nice library! I'm working on a project to build a numeric display that is not flickering on iPhone camera under bright daylight conditions. This was the reason I selected TLC591x as it is not multiplexing/PWMing (if not enabled) LEDs in any way.

The issue is that when pushing the data, all LEDs (including those that should be off) turn on briefly. If the refresh rate is high enough, it causes LEDs in off status to glow a little bit which does not look good visually and consumes additional power from the battery. I use myLED.printDirect(displayArray) function to push the data, the display consists of 5 segments with "pseudo-7 segment LED" (it is 3 LEDs connected in sequence for each segment), I use HW SPI + OE wires connection to the TLC591x, the controller is Arduino Pro Mini.

I was able to find a workaround by changing the code to push the data, now it looks like the following:

myLED.displayDisable();
myLED.printDirect(displayArray);
myLED.displayEnable();

Now it switches off all LEDs by using /OE pin, pushes the data, and then turns LEDs on. This solves the problem with LEDs glowing, but it will reintroduce flickering problem when filmed on camera (as LEDs are going all off before data transfer).

I made two videos in slo-mo to illustrate the issue. The first one is when the data is pushed with with single printDirect() function in a loop. If you look at the green "dot" LED, you will see it blips shortly when data is transferred (actually all red LEDs blips as well, they are just not very well visible in the video).

https://youtube.com/shorts/2qggGIbB9B8

The second one is with displayDisable()->printDirect()->displayEnable() in a loop.

https://youtube.com/shorts/l0aiA3bWOTQ

Can this behavior be fixed in the library or this is chip specific? Unfortunately, I don't have scope to check pulses timing on SPI, can't comment if this can be the problem here.

Thanks and best regards.

Kestas

**Comment by Andy4495** [comment]
Kestas - 

Interesting issue -- I'll take a look. 

Andy

**Comment by Andy4495** [comment]
Kestas - 

I am not able to reproduce the problem on my setup, but I am only testing with a 2-digit LED, and maybe I'm not filming it fast enough. 

However, I did notice something in my code that could potentially cause a flicker. When using Hardware SPI, I am calling toggleLE() an extra time (so LE gets toggled twice in a row without any data in between calls). 

So try this update to the library. Either: 

- Comment out lines 218 and 227 in TLC591x.cpp
  ```cpp
  //    toggleLE();
  ```
- Or, replace TLC591x.cpp with the updated file from the `issue_8` branch on GitHub: 

  <https://github.com/Andy4495/TLC591x/blob/issue_6/src/TLC591x.cpp>

Let me know if that works. 

If it doesn't, then I'll need to look at your code and hardware setup closer.

Thanks,
Andy

**Comment by kestasli** [comment]
Hi Andy, the change fixed the problem, works like charm without any workarounds! Many thanks!

Kestas

**Comment by Andy4495** [comment]
Great! I'll merge in the changes and publish a new release.
